---
language: php
#python: "2.7"
php: "7.0"

sudo: false

addons:
  apt:
    packages:
    - php7.0-cli
    - php7.0-common
    - php7.0-curl
    - python-pip

install:
  # Install Ansible.
  - pip install ansible #==1.9.4

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install required dependencies.
  - ansible-galaxy install geerlingguy.php #,1.9.2

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/test_2_7.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/test_2_8.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/test_3_0.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/test_3_1.yml --syntax-check"
  # Run playbooks
  - "ansible-playbook -i tests/inventory tests/test_2_7.yml --connection=local"
  - "ansible-playbook -i tests/inventory tests/test_2_8.yml --connection=local"
  - "ansible-playbook -i tests/inventory tests/test_3_0.yml --connection=local"
  - "ansible-playbook -i tests/inventory tests/test_3_1.yml --connection=local"
