---
language: php
#python: "2.7"
php: "7.0"

sudo: false

before_install:
  - sudo pip install ansible
  - sudo ansible-galaxy install geerlingguy.php

addons:
  apt:
    packages:
    - php7.0-cli
    - php7.0-common
    - php7.0-curl
    - python-pip

install:
  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/test_2_7.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/test_2_8.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/test_3_0.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/test_3_1.yml --syntax-check"
  # Run playbooks
  - "ansible-playbook -i tests/inventory tests/test_2_7.yml --connection=local"
  - "ansible-playbook -i tests/inventory tests/test_2_8.yml --connection=local"
  - "ansible-playbook -i tests/inventory tests/test_3_0.yml --connection=local"
  - "ansible-playbook -i tests/inventory tests/test_3_1.yml --connection=local"
